task:
  timeout_in: 5m
  container:
    image: gcc:latest
  build_script:
    - sh build.sh -
  amd64_artifacts:
    path: "bin/*"

task:
  timeout_in: 5m
  arm_container:
    image: gcc:latest
  build_script:
    - sh build.sh -
  arm64_artifacts:
    path: "bin/*"
