task:
  timeout_in: 5m
  container:
    image: gcc:latest
  bob_script:
    - git clone https://github.com/inobulles/bob
    - ( cd bob && sh build.sh && sh-bin/bob install )
  build_script:
    - bob test install
  amd64_artifacts:
    path: "bin/*"

task:
  timeout_in: 5m
  arm_container:
    image: gcc:latest
  bob_script:
    - git clone https://github.com/inobulles/bob
    - ( cd bob && sh build.sh && sh-bin/bob install )
  build_script:
    - bob test install
  arm64_artifacts:
    path: "bin/*"
